// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZX0rjEzJjpn7XiYfaIyJMvvWVRm3ro5o',
    appId: '1:811107638568:web:e187180789bc0d756a441d',
    messagingSenderId: '811107638568',
    projectId: 'restaurant-64ae4',
    authDomain: 'restaurant-64ae4.firebaseapp.com',
    storageBucket: 'restaurant-64ae4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcnJv9ykoZGf2AOodyhyELYakXE0VzlE',
    appId: '1:811107638568:android:14cd69e54ffc030e6a441d',
    messagingSenderId: '811107638568',
    projectId: 'restaurant-64ae4',
    storageBucket: 'restaurant-64ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXeAu2Np5FkYMOjdrFh2WDyYQYfo43EC0',
    appId: '1:811107638568:ios:6118526ce9476d966a441d',
    messagingSenderId: '811107638568',
    projectId: 'restaurant-64ae4',
    storageBucket: 'restaurant-64ae4.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );
}
